server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  service-url:
    default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        localtor:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuarios/**
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carros/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/motos/**
