server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka # rama en git
          uri: https://github.com/germannavarro/microservicios.git
          search-paths: config-data
  application:
    name: config-service
      
    
